// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type Task struct {
	ID        string
	Title     string
	Status    string
	Priority  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
