// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	// Backs task.Repository.FindByID. Returns sql.ErrNoRows when absent;
	// infra/postgres/task_repository.go maps that to task.ErrNotFound.
	GetTaskByID(ctx context.Context, id string) (Task, error)
	// Backs task.Repository.FindByTitle. Returns sql.ErrNoRows when
	// absent; infra/postgres/task_repository.go maps that to
	// task.ErrNotFound.
	GetTaskByTitle(ctx context.Context, title string) (Task, error)
	// Backs task.Repository.FindAll. Ordered by created_at for stable,
	// deterministic output (infra/memory has no inherent order since it
	// ranges over a map).
	ListTasks(ctx context.Context) ([]Task, error)
	// SPEC-005 R1/R4: sqlc input for the tasks table (db/migrations/000001_create_tasks.sql).
	// `make sqlc` regenerates infra/postgres/sqlcgen from this file; keep
	// both in the same commit (no drift).
	// Backs task.Repository.Save: insert a new row, or update every
	// mutable column in place when id already exists (matching
	// infra/memory.TaskRepository.Save's upsert-by-id semantics -- see
	// infra/repotest.RunTaskRepositoryContract's "Save called again with
	// the same id upserts" subtest). created_at is intentionally excluded
	// from the DO UPDATE SET list: it must not change on update.
	UpsertTask(ctx context.Context, arg UpsertTaskParams) error
}

var _ Querier = (*Queries)(nil)
