// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"
	"time"
)

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, title, status, priority, created_at, updated_at
FROM tasks
WHERE id = $1
`

// Backs task.Repository.FindByID. Returns sql.ErrNoRows when absent;
// infra/postgres/task_repository.go maps that to task.ErrNotFound.
func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByTitle = `-- name: GetTaskByTitle :one
SELECT id, title, status, priority, created_at, updated_at
FROM tasks
WHERE title = $1
`

// Backs task.Repository.FindByTitle. Returns sql.ErrNoRows when
// absent; infra/postgres/task_repository.go maps that to
// task.ErrNotFound.
func (q *Queries) GetTaskByTitle(ctx context.Context, title string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByTitle, title)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, status, priority, created_at, updated_at
FROM tasks
ORDER BY created_at, id
`

// Backs task.Repository.FindAll. Ordered by created_at for stable,
// deterministic output (infra/memory has no inherent order since it
// ranges over a map).
func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTask = `-- name: UpsertTask :exec

INSERT INTO tasks (id, title, status, priority, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    title      = EXCLUDED.title,
    status     = EXCLUDED.status,
    priority   = EXCLUDED.priority,
    updated_at = EXCLUDED.updated_at
`

type UpsertTaskParams struct {
	ID        string
	Title     string
	Status    string
	Priority  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// SPEC-005 R1/R4: sqlc input for the tasks table (db/migrations/000001_create_tasks.sql).
// `make sqlc` regenerates infra/postgres/sqlcgen from this file; keep
// both in the same commit (no drift).
// Backs task.Repository.Save: insert a new row, or update every
// mutable column in place when id already exists (matching
// infra/memory.TaskRepository.Save's upsert-by-id semantics -- see
// infra/repotest.RunTaskRepositoryContract's "Save called again with
// the same id upserts" subtest). created_at is intentionally excluded
// from the DO UPDATE SET list: it must not change on update.
func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, upsertTask,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
