package jwt

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/srrrs-7/cc-orchestrator/app/auth/domain/token"
)

// fileKeyRing is the on-disk JSON format for the signing key ring.
//
//	{
//	  "active_kid": "...",
//	  "keys": [
//	    { "kid": "...", "private_key_pem": "-----BEGIN RSA PRIVATE KEY-----\n..." },
//	    { "kid": "old-kid", "public_key_pem": "-----BEGIN PUBLIC KEY-----\n..." }
//	  ]
//	}
//
// The file is never committed; it is generated by `make auth-signing-keys`
// and mounted as a volume / secret in production.
type fileKeyRing struct {
	ActiveKid string         `json:"active_kid"`
	Keys      []fileKeyEntry `json:"keys"`
}

// fileKeyEntry mirrors token.KeyEntry on disk. Exactly one of
// private_key_pem (active signing key) or public_key_pem (retired
// verify-only key) should be populated in a well-formed key ring file.
type fileKeyEntry struct {
	Kid           string `json:"kid"`
	PrivateKeyPEM string `json:"private_key_pem,omitempty"`
	PublicKeyPEM  string `json:"public_key_pem,omitempty"`
}

// FileLoader implements token.KeyRingLoader by reading a JSON key ring
// from the file system. It is used when SIGNING_KEYS_FILE is set.
type FileLoader struct {
	path string
}

var _ token.KeyRingLoader = (*FileLoader)(nil)

// NewFileLoader returns a FileLoader that reads from path.
func NewFileLoader(path string) *FileLoader {
	return &FileLoader{path: path}
}

// Load reads and parses the key ring JSON file at f.path. It fails if
// the file is missing, malformed, has an empty active_kid, or has no
// keys.
func (f *FileLoader) Load() (token.SigningMaterial, error) {
	data, err := os.ReadFile(f.path)
	if err != nil {
		return token.SigningMaterial{}, fmt.Errorf("jwt: file loader: read %q: %w", f.path, err)
	}
	var ring fileKeyRing
	if err := json.Unmarshal(data, &ring); err != nil {
		return token.SigningMaterial{}, fmt.Errorf("jwt: file loader: parse %q: %w", f.path, err)
	}
	if ring.ActiveKid == "" {
		return token.SigningMaterial{}, fmt.Errorf("jwt: file loader: %q: active_kid is empty", f.path)
	}
	if len(ring.Keys) == 0 {
		return token.SigningMaterial{}, fmt.Errorf("jwt: file loader: %q: keys array is empty", f.path)
	}
	entries := make([]token.KeyEntry, 0, len(ring.Keys))
	for _, k := range ring.Keys {
		entries = append(entries, token.KeyEntry{
			Kid:           k.Kid,
			PrivateKeyPEM: k.PrivateKeyPEM,
			PublicKeyPEM:  k.PublicKeyPEM,
		})
	}
	return token.SigningMaterial{
		ActiveKid: ring.ActiveKid,
		Keys:      entries,
	}, nil
}
