// Package postgres provides Postgres-backed implementations of the
// domain repository interfaces declared by domain/client,
// domain/user, domain/authcode, and domain/refreshtoken (SPEC-005 R2),
// plus the connection-opening plumbing the composition root
// (cmd/authz/main.go) uses to open the Postgres pool.
//
// Everything in this package that touches SQL goes through
// infra/postgres/sqlcgen (generated by `make sqlc` from
// db/queries/*.sql against db/migrations/*.sql; see sqlc.yaml). The
// only new runtime dependency this package introduces is
// github.com/jackc/pgx/v5, used solely as a database/sql driver (via
// the blank import below) -- every query still goes through
// database/sql, not pgx's native API (plan §1.2 "ドライバ").
//
// Postgres is the sole persistence backend (SPEC-011): fail-closed is
// enforced by Config.Validate (DB_HOST/DB_NAME/DB_USER/DB_PASSWORD
// are required). There is no in-memory fallback.
package postgres

import (
	"context"
	"database/sql"
	"fmt"
	"net/url"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib" // registers the "pgx" database/sql driver name
)

// Config holds the discrete connection parameters used to assemble a
// Postgres DSN (plan §0 "切替の env / DSN": discrete DB_* env vars,
// not a single DATABASE_URL).
//
// Config has no Schema field (removed by the 2026-07-09 refactor, plan
// §RF.2.3): api and auth now each connect to their own dedicated
// Postgres database (Name) instead of sharing one database
// distinguished by connection search_path, so there is nothing left to
// select via a schema/search_path setting. Database creation and
// migration are handled out of band by app/migrator, not this package
// (see .claude/rules/db.md).
//
// A Config value (and in particular its Password field) must never be
// logged or included in an error message wholesale -- see DSN's doc
// comment.
type Config struct {
	Host     string
	Port     string
	Name     string
	User     string
	Password string
	SSLMode  string
}

// Validate reports a configuration error listing only the missing
// required field *names* (never any value, so a missing DB_PASSWORD
// is reported without ever printing a password) when c lacks a value
// required to open a connection, rather than letting DSN silently
// build a malformed connection string. Returns nil when c has every
// required field.
func (c Config) Validate() error {
	var missing []string
	if c.Host == "" {
		missing = append(missing, "DB_HOST")
	}
	if c.Name == "" {
		missing = append(missing, "DB_NAME")
	}
	if c.User == "" {
		missing = append(missing, "DB_USER")
	}
	if c.Password == "" {
		missing = append(missing, "DB_PASSWORD")
	}
	if len(missing) > 0 {
		return fmt.Errorf("postgres: config: missing required variable(s): %v", missing)
	}
	return nil
}

// DSN assembles a libpq-style connection string from c. It sets no
// search_path query parameter: as of the 2026-07-09 refactor, api and
// auth are separated by connecting to distinct databases (c.Name), not
// by schema within a shared one (plan §RF.1.1).
//
// The returned string embeds c.Password in cleartext (as any
// connection string must); callers MUST NOT log it. Open (below)
// never logs the DSN it builds.
func (c Config) DSN() string {
	values := url.Values{}
	values.Set("sslmode", c.SSLMode)

	u := url.URL{
		Scheme:   "postgres",
		User:     url.UserPassword(c.User, c.Password),
		Host:     c.Host + ":" + c.Port,
		Path:     "/" + c.Name,
		RawQuery: values.Encode(),
	}
	return u.String()
}

// Connection pool lifetime bounds applied by Open. These are fixed,
// conservative defaults appropriate for this demo application's
// expected load (a handful of ECS tasks, each opening one pool) --
// not exposed as further configuration, to keep the persistence seam
// simple. These values match app/api/infra/postgres/db.go's Open
// exactly (SPEC-005 review E4, perf B-1/Mn-1): api/auth share one RDS
// instance, so their pool ceilings must stay symmetric.
const (
	maxOpenConns    = 10
	maxIdleConns    = 5
	connMaxLifetime = 30 * time.Minute
	connMaxIdleTime = 5 * time.Minute
)

// pingTimeout bounds how long Open waits for the initial connectivity
// check at startup, independent of the caller's context (which, in
// cmd/authz/main.go, is the long-lived signal.NotifyContext used for
// graceful shutdown -- Open must not block startup, and in turn ECS
// deployment health evaluation/rollback, forever if that context
// happens to already be near cancellation). Matches
// app/api/infra/postgres/db.go's Open exactly (SPEC-005 review E4,
// perf M-1).
const pingTimeout = 5 * time.Second

// Open opens a *sql.DB against the Postgres instance described by
// cfg, registers connection-pool lifetime bounds, and verifies
// connectivity with a bounded Ping before returning, so a
// misconfigured or unreachable database fails fast at startup rather
// than on the first request.
//
// Open itself starts no goroutine and holds no state beyond the
// returned *sql.DB; the caller owns that *sql.DB and MUST call
// Close() on it during graceful shutdown (see cmd/authz/main.go's
// persistence wiring) to release pooled connections. Open does not
// tie the pool's lifetime to ctx: ctx only bounds the initial ping
// (via the fixed pingTimeout, not ctx's own possibly long-lived
// deadline), matching database/sql's own *sql.DB lifecycle model (a
// *sql.DB is a long-lived pool handle, not itself context-scoped).
func Open(ctx context.Context, cfg Config) (*sql.DB, error) {
	if err := cfg.Validate(); err != nil {
		return nil, fmt.Errorf("postgres: open: %w", err)
	}

	db, err := sql.Open("pgx", cfg.DSN())
	if err != nil {
		return nil, fmt.Errorf("postgres: open: %w", err)
	}

	db.SetMaxOpenConns(maxOpenConns)
	db.SetMaxIdleConns(maxIdleConns)
	db.SetConnMaxLifetime(connMaxLifetime)
	db.SetConnMaxIdleTime(connMaxIdleTime)

	pingCtx, cancel := context.WithTimeout(ctx, pingTimeout)
	defer cancel()
	if err := db.PingContext(pingCtx); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("postgres: ping: %w", err)
	}
	return db, nil
}

// OpenPair opens the writer and reader connection pools SPEC-010's
// Reader/Writer split routes queries through. It is the exact
// counterpart of app/api/infra/postgres/db.go's OpenPair (same
// signature, same sharing/failure semantics), kept symmetric across
// both stacks per .claude/rules/db.md.
//
// When readerCfg equals writerCfg (Config is a plain struct of
// comparable string fields, so "==" is ordinary value equality), the
// reader has nowhere distinct to connect to, so OpenPair opens
// exactly one pool (via Open, applying the same pool-size/ping-
// timeout bounds as every other caller of Open) and returns it as
// both writer and reader: the same *sql.DB pointer. This is the
// fail-safe default (SPEC-010 R3 / non-functional "二重に開かない")
// that keeps every existing deployment -- which sets no
// DB_READER_* -- on a single pool exactly as before this Spec.
//
// Only when readerCfg differs from writerCfg does OpenPair open a
// second, independent pool for the reader. If that second Open fails,
// OpenPair closes the already-opened writer pool before returning, so
// a failed OpenPair call never leaks the writer pool back to a caller
// that has no reference to it (the returned writer/reader/closeFn are
// all nil in that case).
//
// On success, closeFn releases every pool OpenPair actually opened,
// exactly once each: closing the shared pool once when reader ==
// writer, or closing both independent pools when they differ. Callers
// (cmd/authz/main.go) should defer closeFn() instead of calling
// writer.Close()/reader.Close() directly, so they don't need to know
// whether the two pools happen to be the same one.
//
// This Spec's fixed wiring decision (docs/plans/SPEC-010-plan.md
// "auth の correctness-critical read の配置") routes user/client reads
// through the reader pool and authcode/refreshtoken reads AND writes
// through the writer pool; that routing lives entirely in
// cmd/authz/main.go's composition, not in this package.
func OpenPair(ctx context.Context, writerCfg, readerCfg Config) (writer, reader *sql.DB, closeFn func() error, err error) {
	writer, err = Open(ctx, writerCfg)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("postgres: open pair: writer: %w", err)
	}

	if readerCfg == writerCfg {
		return writer, writer, writer.Close, nil
	}

	reader, err = Open(ctx, readerCfg)
	if err != nil {
		_ = writer.Close()
		return nil, nil, nil, fmt.Errorf("postgres: open pair: reader: %w", err)
	}

	closeFn = func() error {
		writerErr := writer.Close()
		readerErr := reader.Close()
		if writerErr != nil {
			return writerErr
		}
		return readerErr
	}
	return writer, reader, closeFn, nil
}
