// Package postgres provides Postgres-backed implementations of the
// domain repository interfaces declared by domain/client,
// domain/user and domain/authcode (SPEC-005 R2), plus the
// connection-opening and persistence-mode-selection plumbing the
// composition root (cmd/authz/main.go) uses to choose between this
// package and infra/memory.
//
// Everything in this package that touches SQL goes through
// infra/postgres/sqlcgen (generated by `make sqlc` from
// db/queries/*.sql against db/migrations/*.sql; see sqlc.yaml). The
// only new runtime dependency this package introduces is
// github.com/jackc/pgx/v5, used solely as a database/sql driver (via
// the blank import below) -- every query still goes through
// database/sql, not pgx's native API (plan §1.2 "ドライバ").
package postgres

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/url"
	"os"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib" // registers the "pgx" database/sql driver name
)

// Mode identifies which persistence backend the composition root
// should wire up.
type Mode string

const (
	// ModePostgres selects this package's Postgres-backed repositories.
	ModePostgres Mode = "postgres"
	// ModeMemory selects infra/memory's in-memory repositories.
	ModeMemory Mode = "memory"
)

// Local-development fallback defaults for the discrete DB_* knobs
// that are safe to default (matching docker/postgres/initdb, per
// docs/plans/SPEC-005-plan.md §0). DB_HOST/DB_NAME/DB_USER/DB_PASSWORD
// have no default: see ConfigFromEnv.
const (
	defaultPort    = "5432"
	defaultSSLMode = "disable"
	defaultSchema  = "auth"
)

// ErrPersistenceNotConfigured is returned by SelectMode when neither
// DB_HOST nor a recognized in-memory opt-in APP_ENV value is present.
// This is SPEC-005's fail-closed contract (plan §0 "切替の env / DSN /
// 本番必須強制"): an unset or unrecognized environment (in particular,
// a production deployment that forgot to set DB_HOST) MUST NOT
// silently fall back to in-memory, non-durable, single-instance
// persistence.
var ErrPersistenceNotConfigured = errors.New("postgres: persistence not configured")

// SelectMode decides whether the composition root should use Postgres
// or in-memory persistence:
//
//   - dbHost non-empty                        -> ModePostgres, regardless of appEnv
//   - dbHost empty, appEnv == "local" or "test" -> ModeMemory
//   - dbHost empty, any other appEnv (including "production", "", or
//     an unrecognized value)                  -> a wrapped ErrPersistenceNotConfigured
//
// This is a pure, DB-independent decision (it never dials a network
// connection or reads os.Getenv itself -- callers pass the two values
// explicitly), so it is safe to unit test without a live Postgres
// (docs/plans/SPEC-005-plan.md §5.1).
func SelectMode(dbHost, appEnv string) (Mode, error) {
	if dbHost != "" {
		return ModePostgres, nil
	}
	switch appEnv {
	case "local", "test":
		return ModeMemory, nil
	default:
		return "", fmt.Errorf("postgres: select persistence mode: DB_HOST unset and APP_ENV=%q: %w", appEnv, ErrPersistenceNotConfigured)
	}
}

// Config holds the discrete connection parameters used to assemble a
// Postgres DSN (plan §0 "切替の env / DSN": discrete DB_* env vars,
// not a single DATABASE_URL).
//
// A Config value (and in particular its Password field) must never be
// logged or included in an error message wholesale -- see DSN's doc
// comment.
type Config struct {
	Host     string
	Port     string
	Name     string
	User     string
	Password string
	SSLMode  string
	Schema   string
}

// ConfigFromEnv reads the discrete DB_* environment variables
// (DB_HOST/DB_PORT/DB_NAME/DB_USER/DB_PASSWORD/DB_SSLMODE/DB_SCHEMA)
// and validates that every value required to open a connection is
// present. DB_HOST/DB_NAME/DB_USER/DB_PASSWORD have no default: a
// missing one is reported as a configuration error listing only the
// missing variable *names* (never any value, so a missing
// DB_PASSWORD is reported without ever printing a password) rather
// than silently producing a malformed DSN passed to sql.Open.
// DB_PORT/DB_SSLMODE/DB_SCHEMA fall back to sane local-development
// defaults when unset.
func ConfigFromEnv() (Config, error) {
	cfg := Config{
		Host:     os.Getenv("DB_HOST"),
		Port:     envOrDefault("DB_PORT", defaultPort),
		Name:     os.Getenv("DB_NAME"),
		User:     os.Getenv("DB_USER"),
		Password: os.Getenv("DB_PASSWORD"),
		SSLMode:  envOrDefault("DB_SSLMODE", defaultSSLMode),
		Schema:   envOrDefault("DB_SCHEMA", defaultSchema),
	}

	var missing []string
	if cfg.Host == "" {
		missing = append(missing, "DB_HOST")
	}
	if cfg.Name == "" {
		missing = append(missing, "DB_NAME")
	}
	if cfg.User == "" {
		missing = append(missing, "DB_USER")
	}
	if cfg.Password == "" {
		missing = append(missing, "DB_PASSWORD")
	}
	if len(missing) > 0 {
		return Config{}, fmt.Errorf("postgres: config from env: missing required variable(s): %v", missing)
	}
	return cfg, nil
}

func envOrDefault(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

// DSN assembles a libpq-style connection string from c. Schema is
// applied via the "search_path" query parameter (not a
// schema-qualified DSN path), matching this module's "non-qualified
// migrations/queries + connection search_path" schema-separation
// approach (plan §0 "スキーマ分離機構").
//
// The returned string embeds c.Password in cleartext (as any
// connection string must); callers MUST NOT log it. Open (below)
// never logs the DSN it builds.
func (c Config) DSN() string {
	values := url.Values{}
	values.Set("sslmode", c.SSLMode)
	values.Set("search_path", c.Schema)

	u := url.URL{
		Scheme:   "postgres",
		User:     url.UserPassword(c.User, c.Password),
		Host:     c.Host + ":" + c.Port,
		Path:     "/" + c.Name,
		RawQuery: values.Encode(),
	}
	return u.String()
}

// Connection pool lifetime bounds applied by Open. These are fixed,
// conservative defaults appropriate for this demo application's
// expected load (a handful of ECS tasks, each opening one pool) --
// not exposed as further configuration, to keep the persistence seam
// simple. These values match app/api/infra/postgres/db.go's Open
// exactly (SPEC-005 review E4, perf B-1/Mn-1): api/auth share one RDS
// instance, so their pool ceilings must stay symmetric.
const (
	maxOpenConns    = 10
	maxIdleConns    = 5
	connMaxLifetime = 30 * time.Minute
	connMaxIdleTime = 5 * time.Minute
)

// pingTimeout bounds how long Open waits for the initial connectivity
// check at startup, independent of the caller's context (which, in
// cmd/authz/main.go, is the long-lived signal.NotifyContext used for
// graceful shutdown -- Open must not block startup, and in turn ECS
// deployment health evaluation/rollback, forever if that context
// happens to already be near cancellation). Matches
// app/api/infra/postgres/db.go's Open exactly (SPEC-005 review E4,
// perf M-1).
const pingTimeout = 5 * time.Second

// Open opens a *sql.DB against the Postgres instance described by
// cfg, registers connection-pool lifetime bounds, and verifies
// connectivity with a bounded Ping before returning, so a
// misconfigured or unreachable database fails fast at startup rather
// than on the first request.
//
// Open itself starts no goroutine and holds no state beyond the
// returned *sql.DB; the caller owns that *sql.DB and MUST call
// Close() on it during graceful shutdown (see cmd/authz/main.go's
// persistence wiring) to release pooled connections. Open does not
// tie the pool's lifetime to ctx: ctx only bounds the initial ping
// (via the fixed pingTimeout, not ctx's own possibly long-lived
// deadline), matching database/sql's own *sql.DB lifecycle model (a
// *sql.DB is a long-lived pool handle, not itself context-scoped).
func Open(ctx context.Context, cfg Config) (*sql.DB, error) {
	db, err := sql.Open("pgx", cfg.DSN())
	if err != nil {
		return nil, fmt.Errorf("postgres: open: %w", err)
	}

	db.SetMaxOpenConns(maxOpenConns)
	db.SetMaxIdleConns(maxIdleConns)
	db.SetConnMaxLifetime(connMaxLifetime)
	db.SetConnMaxIdleTime(connMaxIdleTime)

	pingCtx, cancel := context.WithTimeout(ctx, pingTimeout)
	defer cancel()
	if err := db.PingContext(pingCtx); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("postgres: ping: %w", err)
	}
	return db, nil
}
