// Package postgres provides a Postgres-backed infrastructure-layer
// implementation of task.Repository (SPEC-005 R1), plus the
// persistence-selection and connection helpers (db.go) used by
// cmd/api/main.go to choose between infra/memory and infra/postgres at
// startup.
//
// All SQL access goes through infra/postgres/sqlcgen (generated by
// `make sqlc` from db/queries/tasks.sql against the schema in
// db/migrations); this file's only job is translating between that
// generated, storage-shaped API and the domain's task.Task /
// task.Repository contract.
package postgres

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5/pgconn"

	"github.com/srrrs-7/cc-orchestrator/app/api/domain/task"
	"github.com/srrrs-7/cc-orchestrator/app/api/infra/postgres/sqlcgen"
)

// pgUniqueViolation is the Postgres SQLSTATE code for a unique_violation
// (https://www.postgresql.org/docs/current/errcodes-appendix.html).
const pgUniqueViolation = "23505"

// tasksTitleUniqueConstraint is the name Postgres assigns the implicit
// unique index backing `title text NOT NULL UNIQUE` in
// db/migrations/000001_create_tasks.sql (<table>_<column>_key).
const tasksTitleUniqueConstraint = "tasks_title_key"

// TaskRepository is a Postgres-backed implementation of task.Repository.
type TaskRepository struct {
	q *sqlcgen.Queries
}

// var _ task.Repository = (*TaskRepository)(nil) verifies at compile
// time that TaskRepository satisfies the domain's Repository interface,
// the same way infra/memory.TaskRepository does.
var _ task.Repository = (*TaskRepository)(nil)

// NewTaskRepository builds a TaskRepository backed by db. db is not
// owned by the returned TaskRepository: the caller (cmd/api/main.go) is
// responsible for opening and closing it.
func NewTaskRepository(db *sql.DB) *TaskRepository {
	return &TaskRepository{q: sqlcgen.New(db)}
}

// Save inserts or updates t in the tasks table (UpsertTask: INSERT ...
// ON CONFLICT (id) DO UPDATE), matching infra/memory's upsert-by-id
// semantics. A UNIQUE(title) violation -- saving a Task whose title
// already belongs to a different id -- is translated to a
// *task.ConflictError wrapping task.ErrDuplicateTitle (via
// task.NewDuplicateTitleError) rather than leaking a raw database/sql
// or pgx error, so callers can branch with errors.Is/errors.As the
// same way they do against task.DuplicateChecker's pre-check. Any
// other database error is wrapped as a *task.DBError.
func (r *TaskRepository) Save(ctx context.Context, t *task.Task) error {
	err := r.q.UpsertTask(ctx, sqlcgen.UpsertTaskParams{
		ID:        t.ID().String(),
		Title:     t.Title().String(),
		Status:    t.Status().String(),
		Priority:  t.Priority().String(),
		CreatedAt: t.CreatedAt(),
		UpdatedAt: t.UpdatedAt(),
	})
	if err != nil {
		if isUniqueViolation(err, tasksTitleUniqueConstraint) {
			return fmt.Errorf("postgres: save task: %w", task.NewDuplicateTitleError())
		}
		return fmt.Errorf("postgres: save task: %w", task.NewDBError(err))
	}
	return nil
}

// FindByID returns the Task with the given id, or a *task.NotFoundError
// (unwrapping to task.ErrNotFound) if none exists. Any other database
// error is wrapped as a *task.DBError.
func (r *TaskRepository) FindByID(ctx context.Context, id task.ID) (*task.Task, error) {
	row, err := r.q.GetTaskByID(ctx, id.String())
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("postgres: find task by id: %w", task.NewNotFoundError())
		}
		return nil, fmt.Errorf("postgres: find task by id: %w", task.NewDBError(err))
	}
	t, err := taskFromRow(row)
	if err != nil {
		return nil, fmt.Errorf("postgres: find task by id: %w", err)
	}
	return t, nil
}

// FindByTitle returns the Task with the given title, or a
// *task.NotFoundError (unwrapping to task.ErrNotFound) if none exists.
// Any other database error is wrapped as a *task.DBError.
func (r *TaskRepository) FindByTitle(ctx context.Context, title task.Title) (*task.Task, error) {
	row, err := r.q.GetTaskByTitle(ctx, title.String())
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("postgres: find task by title: %w", task.NewNotFoundError())
		}
		return nil, fmt.Errorf("postgres: find task by title: %w", task.NewDBError(err))
	}
	t, err := taskFromRow(row)
	if err != nil {
		return nil, fmt.Errorf("postgres: find task by title: %w", err)
	}
	return t, nil
}

// ListPage returns the Tasks in page -- ordered by created_at, id
// ascending, at most page.Limit() rows starting at page.Offset() (see
// db/queries/tasks.sql: ListTasksPage) -- alongside the total number
// of Tasks in the table regardless of limit/offset (CountTasks). An
// offset at or beyond the total simply yields an empty items slice,
// not an error (SPEC-008 R2/R5).
//
// CountTasks and ListTasksPage are two separate statements rather than
// a single windowed query, so under concurrent writes the returned
// total and items can drift by a small amount relative to each other;
// this is accepted at this sample's scale (SPEC-008 plan risk R-6).
// Any database error from either query is wrapped as a *task.DBError.
func (r *TaskRepository) ListPage(ctx context.Context, page task.Page) ([]*task.Task, int, error) {
	total, err := r.q.CountTasks(ctx)
	if err != nil {
		return nil, 0, fmt.Errorf("postgres: list tasks page: count: %w", task.NewDBError(err))
	}

	rows, err := r.q.ListTasksPage(ctx, sqlcgen.ListTasksPageParams{
		Limit:  int64(page.Limit()),
		Offset: int64(page.Offset()),
	})
	if err != nil {
		return nil, 0, fmt.Errorf("postgres: list tasks page: %w", task.NewDBError(err))
	}

	result := make([]*task.Task, 0, len(rows))
	for _, row := range rows {
		t, err := taskFromRow(row)
		if err != nil {
			return nil, 0, fmt.Errorf("postgres: list tasks page: %w", err)
		}
		result = append(result, t)
	}
	return result, int(total), nil
}

// taskFromRow reconstructs a domain *task.Task from a generated
// sqlcgen.Task row, re-validating every column through the domain's own
// parsers (task.ParseID / task.NewTitle / task.ParseStatus /
// task.ParsePriority) rather than bypassing them. This mirrors
// infra/memory's clone-via-task.Reconstruct boundary: the repository
// never hands out a *task.Task that aliases mutable state it does not
// own, and any row that violates a domain invariant (which should be
// impossible given the CHECK constraints in db/migrations, but is not
// guaranteed for data written by something other than this
// application) surfaces as an explicit error instead of a corrupt
// aggregate.
func taskFromRow(row sqlcgen.Task) (*task.Task, error) {
	id, err := task.ParseID(row.ID)
	if err != nil {
		return nil, task.NewDBError(fmt.Errorf("decode task row id %q: %v", row.ID, err))
	}
	title, err := task.NewTitle(row.Title)
	if err != nil {
		return nil, task.NewDBError(fmt.Errorf("decode task row title %q: %v", row.Title, err))
	}
	status, err := task.ParseStatus(row.Status)
	if err != nil {
		return nil, task.NewDBError(fmt.Errorf("decode task row status %q: %v", row.Status, err))
	}
	priority, err := task.ParsePriority(row.Priority)
	if err != nil {
		return nil, task.NewDBError(fmt.Errorf("decode task row priority %q: %v", row.Priority, err))
	}
	return task.Reconstruct(id, title, status, priority, row.CreatedAt, row.UpdatedAt), nil
}

// isUniqueViolation reports whether err is a Postgres unique_violation
// (SQLSTATE 23505) on the given constraint name. When sql_package:
// database/sql is used (as configured in sqlc.yaml), pgx's stdlib
// driver still surfaces the underlying *pgconn.PgError unwrapped from
// ExecContext/QueryRowContext, so errors.As reaches it directly.
func isUniqueViolation(err error, constraint string) bool {
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) {
		return false
	}
	return pgErr.Code == pgUniqueViolation && pgErr.ConstraintName == constraint
}
