// Package postgres provides a Postgres-backed infrastructure-layer
// implementation of task.Repository (SPEC-005 R1), plus the
// persistence-selection and connection helpers (db.go) used by
// cmd/api/main.go to choose between infra/memory and infra/postgres at
// startup.
//
// SPEC-010 splits the previously single TaskRepository struct into
// TaskReader (task_reader.go) and TaskWriter (task_writer.go), each
// bound to its own *sql.DB pool, so the composition root can route
// reads and writes to different physical connection pools (a future
// read replica for reads, matching this package's OpenPair in
// db.go). This file now holds only the pieces both of those share --
// the row-decoding helper (taskFromRow), the unique-violation
// detection helper (isUniqueViolation) and its supporting constants --
// plus TaskRepository, a thin compatibility composition of the two
// kept so every pre-SPEC-010 caller of NewTaskRepository(db)
// (including the shared repotest contract) continues to compile and
// pass unchanged (SPEC-010 R6).
//
// All SQL access goes through infra/postgres/sqlcgen (generated by
// `make sqlc` from schema/queries/tasks.sql against the schema in
// schema/migrations); this package's job is translating between that
// generated, storage-shaped API and the domain's task.Task /
// task.Reader / task.Writer / task.Repository contracts.
package postgres

import (
	"database/sql"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5/pgconn"

	"github.com/srrrs-7/cc-orchestrator/app/api/domain/task"
	"github.com/srrrs-7/cc-orchestrator/app/api/infra/postgres/sqlcgen"
)

// pgUniqueViolation is the Postgres SQLSTATE code for a unique_violation
// (https://www.postgresql.org/docs/current/errcodes-appendix.html).
const pgUniqueViolation = "23505"

// tasksTitleUniqueConstraint is the name Postgres assigns the implicit
// unique index backing `title text NOT NULL UNIQUE` in
// schema/migrations/000001_create_tasks.sql (<table>_<column>_key).
const tasksTitleUniqueConstraint = "tasks_title_key"

// TaskRepository is the compatibility composition of TaskReader and
// TaskWriter: embedding both promotes FindByID/FindByTitle/ListPage
// (from *TaskReader) and Save (from *TaskWriter), so *TaskRepository
// satisfies task.Repository exactly as the pre-SPEC-010 single-struct
// implementation did. NewTaskRepository backs both halves with the
// same *sql.DB (reader == writer == db), matching the single-pool
// wiring every caller before SPEC-010 relied on.
type TaskRepository struct {
	*TaskReader
	*TaskWriter
}

// var _ task.Repository = (*TaskRepository)(nil) verifies at compile
// time that TaskRepository satisfies the domain's Repository interface,
// the same way infra/memory.TaskRepository does.
var _ task.Repository = (*TaskRepository)(nil)

// NewTaskRepository builds a TaskRepository backed by db. db is not
// owned by the returned TaskRepository: the caller (cmd/api/main.go) is
// responsible for opening and closing it.
//
// This constructor is the pre-SPEC-010 signature, kept for
// compatibility: it wires both TaskReader and TaskWriter to the same
// single db, so a caller not using postgres.OpenPair's reader/writer
// split observes exactly the pre-SPEC-010 single-pool behavior.
// Composition-root code that wants reads and writes routed to
// separate pools should construct NewTaskReader(readerDB) and
// NewTaskWriter(writerDB) directly instead of calling this function.
func NewTaskRepository(db *sql.DB) *TaskRepository {
	return &TaskRepository{NewTaskReader(db), NewTaskWriter(db)}
}

// taskFromRow reconstructs a domain *task.Task from a generated
// sqlcgen.Task row, re-validating every column through the domain's own
// parsers (task.ParseID / task.NewTitle / task.ParseStatus /
// task.ParsePriority) rather than bypassing them. This mirrors
// infra/memory's clone-via-task.Reconstruct boundary: the repository
// never hands out a *task.Task that aliases mutable state it does not
// own, and any row that violates a domain invariant (which should be
// impossible given the CHECK constraints in schema/migrations, but is not
// guaranteed for data written by something other than this
// application) surfaces as an explicit error instead of a corrupt
// aggregate. Shared by TaskReader's FindByID/FindByTitle/ListPage.
func taskFromRow(row sqlcgen.Task) (*task.Task, error) {
	id, err := task.ParseID(row.ID)
	if err != nil {
		return nil, task.NewDBError(fmt.Errorf("decode task row id %q: %v", row.ID, err))
	}
	title, err := task.NewTitle(row.Title)
	if err != nil {
		return nil, task.NewDBError(fmt.Errorf("decode task row title %q: %v", row.Title, err))
	}
	status, err := task.ParseStatus(row.Status)
	if err != nil {
		return nil, task.NewDBError(fmt.Errorf("decode task row status %q: %v", row.Status, err))
	}
	priority, err := task.ParsePriority(row.Priority)
	if err != nil {
		return nil, task.NewDBError(fmt.Errorf("decode task row priority %q: %v", row.Priority, err))
	}
	return task.Reconstruct(id, title, status, priority, row.CreatedAt, row.UpdatedAt), nil
}

// isUniqueViolation reports whether err is a Postgres unique_violation
// (SQLSTATE 23505) on the given constraint name. When sql_package:
// database/sql is used (as configured in sqlc.yaml), pgx's stdlib
// driver still surfaces the underlying *pgconn.PgError unwrapped from
// ExecContext/QueryRowContext, so errors.As reaches it directly.
// Shared by TaskWriter.Save.
func isUniqueViolation(err error, constraint string) bool {
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) {
		return false
	}
	return pgErr.Code == pgUniqueViolation && pgErr.ConstraintName == constraint
}
