// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const getClientByID = `-- name: GetClientByID :one

SELECT id, redirect_uris, allowed_scopes, response_types, grant_types
FROM clients
WHERE id = $1
`

// SPEC-005 R2/R4: sqlc input for the clients table
// (db/migrations/000001_create_auth.sql). `make sqlc` regenerates
// infra/postgres/sqlcgen from this file; keep both in the same commit
// (no drift).
// Backs client.Repository.FindByID. Returns sql.ErrNoRows when
// absent; infra/postgres/client_repository.go maps that to
// client.ErrNotFound.
func (q *Queries) GetClientByID(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.RedirectUris,
		&i.AllowedScopes,
		&i.ResponseTypes,
		&i.GrantTypes,
	)
	return i, err
}

const upsertClient = `-- name: UpsertClient :exec
INSERT INTO clients (id, redirect_uris, allowed_scopes, response_types, grant_types)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    redirect_uris  = EXCLUDED.redirect_uris,
    allowed_scopes = EXCLUDED.allowed_scopes,
    response_types = EXCLUDED.response_types,
    grant_types    = EXCLUDED.grant_types
`

type UpsertClientParams struct {
	ID            string
	RedirectUris  json.RawMessage
	AllowedScopes json.RawMessage
	ResponseTypes json.RawMessage
	GrantTypes    json.RawMessage
}

// Backs the startup idempotent seed (infra/postgres/seed.go's
// SeedClient), not client.Repository itself (which is read-only).
// Inserts a new row, or overwrites every column in place when id
// already exists, so repeated process starts converge on the same
// seed data rather than erroring on the second run.
func (q *Queries) UpsertClient(ctx context.Context, arg UpsertClientParams) error {
	_, err := q.db.ExecContext(ctx, upsertClient,
		arg.ID,
		arg.RedirectUris,
		arg.AllowedScopes,
		arg.ResponseTypes,
		arg.GrantTypes,
	)
	return err
}
