// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getClientByID = `-- name: GetClientByID :one

SELECT id, redirect_uris, allowed_scopes, response_types, grant_types, client_secret_hash
FROM clients
WHERE id = $1
`

// SPEC-005 R2/R4: sqlc input for the clients table
// (schema/migrations/000001_create_auth.sql). `make sqlc` regenerates
// infra/postgres/sqlcgen from this file; keep both in the same commit
// (no drift).
// Backs client.Repository.FindByID. Returns sql.ErrNoRows when
// absent; infra/postgres/client_repository.go maps that to
// client.ErrNotFound.
func (q *Queries) GetClientByID(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.RedirectUris,
		&i.AllowedScopes,
		&i.ResponseTypes,
		&i.GrantTypes,
		&i.ClientSecretHash,
	)
	return i, err
}

const upsertClient = `-- name: UpsertClient :exec
INSERT INTO clients (id, redirect_uris, allowed_scopes, response_types, grant_types, client_secret_hash)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    redirect_uris       = EXCLUDED.redirect_uris,
    allowed_scopes      = EXCLUDED.allowed_scopes,
    response_types      = EXCLUDED.response_types,
    grant_types         = EXCLUDED.grant_types,
    client_secret_hash  = EXCLUDED.client_secret_hash
`

type UpsertClientParams struct {
	ID               string
	RedirectUris     json.RawMessage
	AllowedScopes    json.RawMessage
	ResponseTypes    json.RawMessage
	GrantTypes       json.RawMessage
	ClientSecretHash sql.NullString
}

// Backs the startup idempotent seed (infra/postgres/seed.go's
// SeedClient), not client.Repository itself (which is read-only).
// Inserts a new row, or overwrites every column in place when id
// already exists, so repeated process starts converge on the same
// seed data rather than erroring on the second run.
// client_secret_hash is NULL for public clients, non-NULL (bcrypt hash)
// for confidential clients (ISSUE-035).
func (q *Queries) UpsertClient(ctx context.Context, arg UpsertClientParams) error {
	_, err := q.db.ExecContext(ctx, upsertClient,
		arg.ID,
		arg.RedirectUris,
		arg.AllowedScopes,
		arg.ResponseTypes,
		arg.GrantTypes,
		arg.ClientSecretHash,
	)
	return err
}
