// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consents.sql

package sqlcgen

import (
	"context"
)

const deleteConsentsByClientID = `-- name: DeleteConsentsByClientID :exec
DELETE FROM consents WHERE client_id = $1
`

func (q *Queries) DeleteConsentsByClientID(ctx context.Context, clientID string) error {
	_, err := q.db.ExecContext(ctx, deleteConsentsByClientID, clientID)
	return err
}

const deleteConsentsByUserID = `-- name: DeleteConsentsByUserID :exec
DELETE FROM consents WHERE user_id = $1
`

func (q *Queries) DeleteConsentsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteConsentsByUserID, userID)
	return err
}

const hasConsent = `-- name: HasConsent :one

SELECT EXISTS(
    SELECT 1
    FROM consents
    WHERE user_id = $1 AND client_id = $2 AND scope = $3
) AS has_consent
`

type HasConsentParams struct {
	UserID   string
	ClientID string
	Scope    string
}

// ISSUE-032: sqlc input for consents (schema/migrations/000004_create_consents.sql).
func (q *Queries) HasConsent(ctx context.Context, arg HasConsentParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasConsent, arg.UserID, arg.ClientID, arg.Scope)
	var has_consent bool
	err := row.Scan(&has_consent)
	return has_consent, err
}

const upsertConsent = `-- name: UpsertConsent :exec
INSERT INTO consents (user_id, client_id, scope)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, client_id, scope) DO UPDATE SET
    granted_at = EXCLUDED.granted_at
`

type UpsertConsentParams struct {
	UserID   string
	ClientID string
	Scope    string
}

func (q *Queries) UpsertConsent(ctx context.Context, arg UpsertConsentParams) error {
	_, err := q.db.ExecContext(ctx, upsertConsent, arg.UserID, arg.ClientID, arg.Scope)
	return err
}
