// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AuthorizationCode struct {
	Code            string
	ClientID        string
	UserID          string
	RedirectUri     string
	Scope           string
	Nonce           sql.NullString
	Challenge       string
	ChallengeMethod string
	ExpiresAt       time.Time
	Consumed        bool
	CreatedAt       time.Time
	AuthTime        sql.NullTime
}

type Client struct {
	ID               string
	RedirectUris     json.RawMessage
	AllowedScopes    json.RawMessage
	ResponseTypes    json.RawMessage
	GrantTypes       json.RawMessage
	ClientSecretHash sql.NullString
}

type Consent struct {
	UserID    string
	ClientID  string
	Scope     string
	GrantedAt time.Time
}

type RefreshToken struct {
	TokenHash string
	FamilyID  string
	ClientID  string
	UserID    string
	Scope     string
	ExpiresAt time.Time
	Consumed  bool
	CreatedAt time.Time
	AuthTime  sql.NullTime
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	ProfileName  string
	ProfileEmail string
}
