// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"time"
)

type Querier interface {
	// Backs authcode.Repository.Consume: the sole, atomic single-use
	// mechanism (plan §0 "authcode 単回使用/TTL"). DELETE ... RETURNING is
	// a single statement, so Postgres's own row-level locking guarantees
	// that when two callers race to consume the same code, exactly one
	// DELETE removes (and thus "wins") the row; the loser's statement
	// affects zero rows. Returns sql.ErrNoRows (0 rows deleted) when no
	// row with this code exists at all -- this covers both a genuinely
	// unknown code and a repeat consume of an already-consumed
	// (already-deleted) one, which infra/postgres/authcode_repository.go
	// maps to authcode.ErrNotFound. When a row IS deleted, the caller
	// compares the returned expires_at against time.Now() to distinguish
	// a valid consume (nil) from a consume of an expired-but-not-yet-
	// lazily-evicted row (authcode.ErrExpired), matching
	// infra/memory.AuthCodeRepository.Consume's expiry check.
	ConsumeAuthCode(ctx context.Context, code string) (time.Time, error)
	// Lazy eviction companion to GetActiveAuthCode: called by
	// infra/postgres/authcode_repository.go after GetActiveAuthCode finds
	// no active row, to opportunistically remove a code that exists but
	// has expired, so expired codes do not accumulate. The expires_at
	// <= now() guard makes this a no-op (not an error) if code does not
	// exist or has not actually expired.
	DeleteExpiredAuthCode(ctx context.Context, code string) error
	// Backs authcode.Repository.FindByCode. Only a row that is both
	// unconsumed and not yet past its TTL is "active"; an expired row is
	// invisible here even though it still physically exists until
	// DeleteExpiredAuthCode lazily removes it (matching
	// infra/memory.AuthCodeRepository.FindByCode's "expired looks like
	// not-found" contract). Returns sql.ErrNoRows when no active row
	// matches; infra/postgres/authcode_repository.go maps that to
	// authcode.ErrNotFound.
	GetActiveAuthCode(ctx context.Context, code string) (GetActiveAuthCodeRow, error)
	// SPEC-005 R2/R4: sqlc input for the clients table
	// (db/migrations/000001_create_auth.sql). `make sqlc` regenerates
	// infra/postgres/sqlcgen from this file; keep both in the same commit
	// (no drift).
	// Backs client.Repository.FindByID. Returns sql.ErrNoRows when
	// absent; infra/postgres/client_repository.go maps that to
	// client.ErrNotFound.
	GetClientByID(ctx context.Context, id string) (Client, error)
	// SPEC-005 R2/R4: sqlc input for the users table
	// (db/migrations/000001_create_auth.sql). `make sqlc` regenerates
	// infra/postgres/sqlcgen from this file; keep both in the same commit
	// (no drift).
	// Backs user.Repository.FindByID. Returns sql.ErrNoRows when absent;
	// infra/postgres/user_repository.go maps that to user.ErrNotFound.
	GetUserByID(ctx context.Context, id string) (User, error)
	// Backs user.Repository.FindByUsername. username is UNIQUE (see the
	// migration), so at most one row ever matches. Returns sql.ErrNoRows
	// when absent; infra/postgres/user_repository.go maps that to
	// user.ErrNotFound.
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// SPEC-005 R2/R4: sqlc input for the authorization_codes table
	// (db/migrations/000001_create_auth.sql). `make sqlc` regenerates
	// infra/postgres/sqlcgen from this file; keep both in the same commit
	// (no drift).
	// Backs authcode.Repository.Save: authorization codes are
	// issue-once/consume-once, so this is a plain INSERT (not an upsert --
	// a code colliding with an existing primary key would indicate a
	// broken random generator, not a legitimate re-save).
	InsertAuthCode(ctx context.Context, arg InsertAuthCodeParams) error
	// Backs the startup idempotent seed (infra/postgres/seed.go's
	// SeedClient), not client.Repository itself (which is read-only).
	// Inserts a new row, or overwrites every column in place when id
	// already exists, so repeated process starts converge on the same
	// seed data rather than erroring on the second run.
	UpsertClient(ctx context.Context, arg UpsertClientParams) error
	// Backs the startup idempotent seed (infra/postgres/seed.go's
	// SeedUser), not user.Repository itself (which is read-only). Inserts
	// a new row, or overwrites every column in place when id already
	// exists, so repeated process starts converge on the same seed data
	// rather than erroring on the second run.
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
