// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE refresh_tokens
SET consumed = true
WHERE token_hash = $1 AND consumed = false AND expires_at > now()
RETURNING token_hash
`

// Backs the "consume old" half of refreshtoken.Repository.Rotate
// (SPEC-006 付録 A): the sole, atomic single-use mechanism for a
// refresh token, the RefreshToken analogue of ConsumeAuthCode.
// UPDATE ... RETURNING is a single statement, so Postgres's own
// row-level locking guarantees that when two callers race to rotate
// the same token, exactly one UPDATE flips consumed (and thus "wins")
// and every other caller's statement affects zero rows. Returns
// sql.ErrNoRows (0 rows updated) both when token_hash does not exist
// at all, has already expired, or -- critically -- already has
// consumed = true (the WHERE clause's `consumed = false` guard is
// what makes an already-consumed row invisible here, rather than
// being re-flipped). infra/postgres/refreshtoken_repository.go
// distinguishes these zero-rows cases (ErrReused vs ErrNotFound) with
// a follow-up GetRefreshToken call in the same transaction, per 付録
// A's precedence rule.
func (q *Queries) ConsumeRefreshToken(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRowContext(ctx, consumeRefreshToken, tokenHash)
	var token_hash string
	err := row.Scan(&token_hash)
	return token_hash, err
}

const deleteExpiredRefreshToken = `-- name: DeleteExpiredRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token_hash = $1 AND expires_at <= now()
`

// Lazy eviction companion to GetRefreshToken, mirroring
// DeleteExpiredAuthCode: called after GetRefreshToken finds no
// non-expired row, to opportunistically remove a row that exists but
// has expired, so expired refresh tokens do not accumulate. The
// expires_at <= now() guard makes this a no-op (not an error) if
// token_hash does not exist or has not actually expired.
func (q *Queries) DeleteExpiredRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRefreshToken, tokenHash)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT token_hash, family_id, client_id, user_id, scope, expires_at, consumed, auth_time
FROM refresh_tokens
WHERE token_hash = $1 AND expires_at > now()
`

type GetRefreshTokenRow struct {
	TokenHash string
	FamilyID  string
	ClientID  string
	UserID    string
	Scope     string
	ExpiresAt time.Time
	Consumed  bool
	AuthTime  sql.NullTime
}

// Backs refreshtoken.Repository.FindByTokenHash. Unlike
// GetActiveAuthCode, this query is deliberately NOT filtered by
// `consumed = false`: a consumed-but-unexpired row must still be
// returned so the caller can detect a replay of an already-rotated
// token (SPEC-006 付録 A's FindByTokenHash doc comment -- reuse
// detection needs to see it before it even reaches Rotate). Only
// expiry hides a row here; expired rows are lazily evicted by
// DeleteExpiredRefreshToken below. Returns sql.ErrNoRows when no
// non-expired row matches; infra/postgres/refreshtoken_repository.go
// maps that to refreshtoken.ErrNotFound (after opportunistically
// evicting an expired row, if any).
func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, tokenHash)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.TokenHash,
		&i.FamilyID,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.ExpiresAt,
		&i.Consumed,
		&i.AuthTime,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec

INSERT INTO refresh_tokens (
    token_hash, family_id, client_id, user_id, scope, expires_at, consumed, auth_time
) VALUES (
    $1, $2, $3, $4, $5, $6, false, $7
)
`

type InsertRefreshTokenParams struct {
	TokenHash string
	FamilyID  string
	ClientID  string
	UserID    string
	Scope     string
	ExpiresAt time.Time
	AuthTime  sql.NullTime
}

// SPEC-006 R4/R5/R8: sqlc input for the refresh_tokens table
// (schema/migrations/000002_create_refresh_tokens.sql). `make sqlc`
// regenerates infra/postgres/sqlcgen from this file; keep both in the
// same commit (no drift).
// Backs refreshtoken.Repository.Save (the initial refresh token minted
// at authorization_code exchange) and the "insert newRT" half of
// Rotate's atomic consume-old + insert-new transaction. It is a plain
// INSERT, not an upsert: a token_hash collision would indicate a
// broken random generator, not a legitimate re-save (mirrors
// InsertAuthCode's doc comment in authcodes.sql).
// auth_time ($7) is the OIDC IdP session login timestamp carried forward
// through rotation; NULL means not available (maps to time.Time{} in Go --
// see ISSUE-038).
func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken,
		arg.TokenHash,
		arg.FamilyID,
		arg.ClientID,
		arg.UserID,
		arg.Scope,
		arg.ExpiresAt,
		arg.AuthTime,
	)
	return err
}

const revokeFamilyRefreshTokens = `-- name: RevokeFamilyRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE family_id = $1
`

// Backs refreshtoken.Repository.RevokeFamily: the reuse-detection
// response (RFC 9700 4.14) that invalidates every token in a rotation
// chain (both active and already-consumed rows) in one statement, so
// a stolen token cannot yield further tokens. Deleting zero rows (an
// unknown or already-empty family_id) is not an error -- idempotent,
// matching Repository.RevokeFamily's doc comment.
func (q *Queries) RevokeFamilyRefreshTokens(ctx context.Context, familyID string) error {
	_, err := q.db.ExecContext(ctx, revokeFamilyRefreshTokens, familyID)
	return err
}
