// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one

SELECT id, username, password, profile_name, profile_email
FROM users
WHERE id = $1
`

// SPEC-005 R2/R4: sqlc input for the users table
// (db/migrations/000001_create_auth.sql). `make sqlc` regenerates
// infra/postgres/sqlcgen from this file; keep both in the same commit
// (no drift).
// Backs user.Repository.FindByID. Returns sql.ErrNoRows when absent;
// infra/postgres/user_repository.go maps that to user.ErrNotFound.
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.ProfileName,
		&i.ProfileEmail,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, profile_name, profile_email
FROM users
WHERE username = $1
`

// Backs user.Repository.FindByUsername. username is UNIQUE (see the
// migration), so at most one row ever matches. Returns sql.ErrNoRows
// when absent; infra/postgres/user_repository.go maps that to
// user.ErrNotFound.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.ProfileName,
		&i.ProfileEmail,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, username, password, profile_name, profile_email)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    username      = EXCLUDED.username,
    password      = EXCLUDED.password,
    profile_name  = EXCLUDED.profile_name,
    profile_email = EXCLUDED.profile_email
`

type UpsertUserParams struct {
	ID           string
	Username     string
	Password     string
	ProfileName  string
	ProfileEmail string
}

// Backs the startup idempotent seed (infra/postgres/seed.go's
// SeedUser), not user.Repository itself (which is read-only). Inserts
// a new row, or overwrites every column in place when id already
// exists, so repeated process starts converge on the same seed data
// rather than erroring on the second run.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.ProfileName,
		arg.ProfileEmail,
	)
	return err
}
